  Normal   Pulled     4m14s                 kubelet            Successfully pulled image "saksham8000/ai-idp-platform:7" in 148ms (148ms including waiting). Image size: 63479943 bytes.
  Warning  BackOff    4m7s (x9 over 5m1s)   kubelet            Back-off restarting failed container ai-idp-platform in pod ai-idp-platform-6f7fbdf84f-rq55l_platform-system(0424cf31-e72a-4fa3-87c2-dba9e0137d40)
root@kubernetes-master:/home/ubuntu#
