apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-idp-platform
  namespace: platform-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-idp-platform

  template:
    metadata:
      labels:
        app: ai-idp-platform

    spec:
      containers:

        - name: ai-idp-platform

          image: saksham8000/ai-idp-platform:1

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://platform:platform123@postgres-service.platform-system.svc.cluster.local:5432/platformdb"