apiVersion: v1
kind: Service

metadata:
  name: ai-idp-platform-service
  namespace: platform-system

spec:
  type: NodePort

  selector:
    app: ai-idp-platform

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
